#! /bin/bash

if [[ "$(docker images -q burgundy/mynginx:latest 2> /dev/null)" == "" ]]; then
	docker build -f nginx/Dockerfile --no-cache -t burgundy/mynginx nginx/
fi
docker build -f DockerfileStageTwo --no-cache -t burgundy/timeslot .

