version: '3.2'

services:
  web:
    image: burgundy/timeslot:latest
    ports:
      - 9000:9000
      - 9443:9443
    deploy:
      replicas: 1
    networks:
      - webnet

  nginx:
    restart: always
    image: nginx:stable-alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
    networks:
      - webnet

networks:
  webnet:
