version: '3'

services:
  web:
    image: burgundy/timeslot:latest
    ports:
      - 9000:9000
      - 9443:9443
    deploy:
      replicas: 1
    networks:
      - webnet

  nginx:
    image: burgundy/mynginx:latest
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
    networks:
      - webnet






networks:
  webnet:
