#! /bin/bash

docker run --rm  -p 443:443 -p 80:80 --name letsencrypt  -v "/etc/letsencrypt:/etc/letsencrypt" \
 -v "/var/lib/letsencrypt:/var/lib/letsencrypt"  certbot/certbot certonly -n -m "cahill@mtu.edu" \
 -d lazydomainname.net --standalone --agree-tos
